version: 2
updates:
  - package-ecosystem: npm
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action/*"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
