import type { McpToolsetName } from "./constants.js"

export const MCP_RESOURCE_NAMES = Object.freeze({
  activity: "connector_activity",
  defaultSoundboard: "default_soundboard_sounds",
  guilds: "scoped_guilds",
  gatewayEvents: "gateway_events",
  gatewayStatus: "gateway_status",
  observability: "connector_observability",
  policy: "connector_policy",
  safety: "connector_safety",
})

export const MCP_RESOURCE_URIS = Object.freeze({
  activity: "discord://connector/activity",
  defaultSoundboard: "discord://soundboard/defaults",
  guilds: "discord://guilds",
  gatewayEvents: "discord://gateway/events",
  gatewayStatus: "discord://gateway/status",
  observability: "discord://connector/observability",
  policy: "discord://connector/policy",
  safety: "discord://connector/safety",
})

export const MCP_RESOURCE_TEMPLATE_NAMES = Object.freeze({
  channelAccess: "channel_access",
  channelMetadata: "channel_metadata",
  channelPermissionOverwrites: "channel_permission_overwrites",
  channelStageInstance: "channel_stage_instance",
  channelWebhooks: "channel_webhooks",
  exactGuildBan: "exact_guild_ban",
  exactGuildInvite: "exact_guild_invite",
  exactMember: "exact_member",
  exactMessage: "exact_message",
  exactRole: "exact_role",
  exactGuildSoundboardSound: "exact_guild_soundboard_sound",
  guildAutomodRules: "guild_automod_rules",
  guildOnboarding: "guild_onboarding",
  guildWelcomeScreen: "guild_welcome_screen",
  guildWidgetSettings: "guild_widget_settings",
  guildChannels: "guild_channels",
  guildEmojis: "guild_emojis",
  guildRoles: "guild_roles",
  guildScheduledEvents: "guild_scheduled_events",
  guildSoundboard: "guild_soundboard",
  guildStickers: "guild_stickers",
  memberVoiceState: "member_voice_state",
  threadMembership: "thread_membership",
  threadState: "thread_state",
})

export const MCP_RESOURCE_TEMPLATE_URIS = Object.freeze({
  channelAccess: "discord://channels/{channelId}/access",
  channelMetadata: "discord://channels/{channelId}",
  channelPermissionOverwrites: "discord://channels/{channelId}/permission-overwrites",
  channelStageInstance: "discord://guilds/{guildId}/channels/{channelId}/stage-instance",
  channelWebhooks: "discord://channels/{channelId}/webhooks",
  exactGuildBan: "discord://guilds/{guildId}/bans/{userId}",
  exactGuildInvite: "discord://guilds/{guildId}/invites/{inviteRef}",
  exactMember: "discord://guilds/{guildId}/members/{userId}",
  exactMessage: "discord://channels/{channelId}/messages/{messageId}",
  exactRole: "discord://guilds/{guildId}/roles/{roleId}",
  exactGuildSoundboardSound: "discord://guilds/{guildId}/soundboard/{soundId}",
  guildAutomodRules: "discord://guilds/{guildId}/automod-rules",
  guildOnboarding: "discord://guilds/{guildId}/onboarding",
  guildWelcomeScreen: "discord://guilds/{guildId}/welcome-screen",
  guildWidgetSettings: "discord://guilds/{guildId}/widget-settings",
  guildChannels: "discord://guilds/{guildId}/channels",
  guildEmojis: "discord://guilds/{guildId}/emojis",
  guildRoles: "discord://guilds/{guildId}/roles",
  guildScheduledEvents: "discord://guilds/{guildId}/scheduled-events",
  guildSoundboard: "discord://guilds/{guildId}/soundboard",
  guildStickers: "discord://guilds/{guildId}/stickers",
  memberVoiceState: "discord://guilds/{guildId}/members/{userId}/voice-state",
  threadMembership: "discord://guilds/{guildId}/threads/{threadId}/members/{userId}",
  threadState: "discord://guilds/{guildId}/threads/{threadId}",
})

export const MCP_PROMPT_NAMES = Object.freeze({
  findGuildMembers: "find_guild_members",
  inspectGuildBan: "inspect_guild_ban",
  reviewInviteDeletion: "review_invite_deletion",
  reviewOnboardingChange: "review_onboarding_change",
  reviewWelcomeScreenChange: "review_welcome_screen_change",
  reviewWidgetSettingsChange: "review_widget_settings_change",
  reviewAttachmentMessage: "review_attachment_message",
  reviewAutomodChange: "review_automod_change",
  reviewChannelCreation: "review_channel_creation",
  reviewChannelMetadataChange: "review_channel_metadata_change",
  reviewChannelPermissionOverwrite: "review_channel_permission_overwrite",
  reviewForumPost: "review_forum_post",
  reviewGuildExpressionChange: "review_guild_expression_change",
  reviewSoundboardChange: "review_soundboard_change",
  reviewGuildScaffold: "review_guild_scaffold",
  reviewMemberModeration: "review_member_moderation",
  reviewMemberRoleChange: "review_member_role_change",
  reviewMemberVoiceChange: "review_member_voice_change",
  reviewThreadChange: "review_thread_change",
  reviewMessageDeletion: "review_message_deletion",
  reviewMessagePin: "review_message_pin",
  reviewRoleCreation: "review_role_creation",
  reviewRoleConfiguration: "review_role_configuration",
  reviewScheduledEventChange: "review_scheduled_event_change",
  reviewStageInstanceChange: "review_stage_instance_change",
  reviewWebhookDeletion: "review_webhook_deletion",
  searchGuildMessages: "search_guild_messages",
  summarizeChannel: "summarize_channel",
})

export type McpPromptName = typeof MCP_PROMPT_NAMES[
  keyof typeof MCP_PROMPT_NAMES
]

export const MCP_PROMPT_TOOLSETS = Object.freeze({
  [MCP_PROMPT_NAMES.findGuildMembers]: "members",
  [MCP_PROMPT_NAMES.inspectGuildBan]: "bans",
  [MCP_PROMPT_NAMES.reviewInviteDeletion]: "invites",
  [MCP_PROMPT_NAMES.reviewOnboardingChange]: "onboarding",
  [MCP_PROMPT_NAMES.reviewWelcomeScreenChange]: "welcome-screen",
  [MCP_PROMPT_NAMES.reviewWidgetSettingsChange]: "widget-settings",
  [MCP_PROMPT_NAMES.reviewAttachmentMessage]: "attachments",
  [MCP_PROMPT_NAMES.reviewAutomodChange]: "automod",
  [MCP_PROMPT_NAMES.reviewChannelCreation]: "channel-creation",
  [MCP_PROMPT_NAMES.reviewChannelMetadataChange]: "channel-metadata",
  [MCP_PROMPT_NAMES.reviewChannelPermissionOverwrite]: "permission-overwrites",
  [MCP_PROMPT_NAMES.reviewForumPost]: "forum-posts",
  [MCP_PROMPT_NAMES.reviewGuildExpressionChange]: "guild-expressions",
  [MCP_PROMPT_NAMES.reviewSoundboardChange]: "soundboard",
  [MCP_PROMPT_NAMES.reviewGuildScaffold]: "guild-scaffolds",
  [MCP_PROMPT_NAMES.reviewMemberModeration]: "moderation",
  [MCP_PROMPT_NAMES.reviewMemberRoleChange]: "member-roles",
  [MCP_PROMPT_NAMES.reviewMemberVoiceChange]: "voice-moderation",
  [MCP_PROMPT_NAMES.reviewThreadChange]: "thread-governance",
  [MCP_PROMPT_NAMES.reviewMessageDeletion]: "deletion",
  [MCP_PROMPT_NAMES.reviewMessagePin]: "pins",
  [MCP_PROMPT_NAMES.reviewRoleCreation]: "role-creation",
  [MCP_PROMPT_NAMES.reviewRoleConfiguration]: "role-configuration",
  [MCP_PROMPT_NAMES.reviewScheduledEventChange]: "scheduled-events",
  [MCP_PROMPT_NAMES.reviewStageInstanceChange]: "stage-instances",
  [MCP_PROMPT_NAMES.reviewWebhookDeletion]: "webhooks",
  [MCP_PROMPT_NAMES.searchGuildMessages]: "messages",
  [MCP_PROMPT_NAMES.summarizeChannel]: "messages",
} satisfies Record<McpPromptName, McpToolsetName>)

export function selectedMcpPromptNames(
  toolsets: ReadonlySet<McpToolsetName>,
): McpPromptName[] {
  return (Object.values(MCP_PROMPT_NAMES) as McpPromptName[])
    .filter((name) => toolsets.has(MCP_PROMPT_TOOLSETS[name]))
}
