import type { McpToolsetName } from "./constants.js"

export const MCP_RESOURCE_NAMES = Object.freeze({
  activity: "connector_activity",
  applicationEmojis: "application_emojis",
  applicationPosture: "application_posture",
  defaultSoundboard: "default_soundboard_sounds",
  guilds: "scoped_guilds",
  gatewayEvents: "gateway_events",
  gatewayStatus: "gateway_status",
  nativeInteractionPending: "pending_native_interactions",
  nativeInteractionStatus: "native_interaction_status",
  observability: "connector_observability",
  planReviewApp: "plan_review_app",
  policy: "connector_policy",
  safety: "connector_safety",
  voiceRegions: "voice_regions",
})

export const MCP_RESOURCE_URIS = Object.freeze({
  activity: "discord://connector/activity",
  applicationEmojis: "discord://application/emojis",
  applicationPosture: "discord://application/posture",
  defaultSoundboard: "discord://soundboard/defaults",
  guilds: "discord://guilds",
  gatewayEvents: "discord://gateway/events",
  gatewayStatus: "discord://gateway/status",
  nativeInteractionPending: "discord://interactions/pending",
  nativeInteractionStatus: "discord://interactions/status",
  observability: "discord://connector/observability",
  planReviewApp: "ui://discord-mcp/plan-review",
  policy: "discord://connector/policy",
  safety: "discord://connector/safety",
  voiceRegions: "discord://voice/regions",
})

export const MCP_RESOURCE_TEMPLATE_NAMES = Object.freeze({
  channelAccess: "channel_access",
  channelAnnouncementSubscriptions: "channel_announcement_subscriptions",
  channelDeletionReadiness: "channel_deletion_readiness",
  channelForumTags: "channel_forum_tags",
  channelMetadata: "channel_metadata",
  channelVoiceStatus: "channel_voice_status",
  channelPermissionOverwrites: "channel_permission_overwrites",
  channelStageInstance: "channel_stage_instance",
  channelWebhooks: "channel_webhooks",
  exactGuildBan: "exact_guild_ban",
  exactGuildInvite: "exact_guild_invite",
  exactMember: "exact_member",
  exactMessage: "exact_message",
  messageReactions: "message_reactions",
  exactRole: "exact_role",
  exactGuildSoundboardSound: "exact_guild_soundboard_sound",
  guildAutomodRules: "guild_automod_rules",
  guildOnboarding: "guild_onboarding",
  guildIncidentActions: "guild_incident_actions",
  guildProfile: "guild_profile",
  guildWelcomeScreen: "guild_welcome_screen",
  guildWidgetSettings: "guild_widget_settings",
  guildSettings: "guild_settings",
  guildChannels: "guild_channels",
  guildChannelOrder: "guild_channel_order",
  guildEmojis: "guild_emojis",
  guildRoles: "guild_roles",
  guildRoleOrder: "guild_role_order",
  roleDeletionReadiness: "role_deletion_readiness",
  guildScheduledEvents: "guild_scheduled_events",
  guildSoundboard: "guild_soundboard",
  guildStickers: "guild_stickers",
  guildTemplates: "guild_templates",
  guildVoiceRegions: "guild_voice_regions",
  guildIntegrations: "guild_integrations",
  memberVoiceState: "member_voice_state",
  threadMembership: "thread_membership",
  threadState: "thread_state",
})

export const MCP_RESOURCE_TEMPLATE_URIS = Object.freeze({
  channelAccess: "discord://channels/{channelId}/access",
  channelAnnouncementSubscriptions: "discord://channels/{channelId}/announcement-subscriptions",
  channelDeletionReadiness: "discord://guilds/{guildId}/channels/{channelId}/deletion-readiness",
  channelForumTags: "discord://channels/{channelId}/forum-tags",
  channelMetadata: "discord://channels/{channelId}",
  channelVoiceStatus: "discord://guilds/{guildId}/channels/{channelId}/voice-status",
  channelPermissionOverwrites: "discord://channels/{channelId}/permission-overwrites",
  channelStageInstance: "discord://guilds/{guildId}/channels/{channelId}/stage-instance",
  channelWebhooks: "discord://channels/{channelId}/webhooks",
  exactGuildBan: "discord://guilds/{guildId}/bans/{userId}",
  exactGuildInvite: "discord://guilds/{guildId}/invites/{inviteRef}",
  exactMember: "discord://guilds/{guildId}/members/{userId}",
  exactMessage: "discord://channels/{channelId}/messages/{messageId}",
  messageReactions: "discord://channels/{channelId}/messages/{messageId}/reactions",
  exactRole: "discord://guilds/{guildId}/roles/{roleId}",
  exactGuildSoundboardSound: "discord://guilds/{guildId}/soundboard/{soundId}",
  guildAutomodRules: "discord://guilds/{guildId}/automod-rules",
  guildOnboarding: "discord://guilds/{guildId}/onboarding",
  guildIncidentActions: "discord://guilds/{guildId}/incident-actions",
  guildProfile: "discord://guilds/{guildId}/profile",
  guildWelcomeScreen: "discord://guilds/{guildId}/welcome-screen",
  guildWidgetSettings: "discord://guilds/{guildId}/widget-settings",
  guildSettings: "discord://guilds/{guildId}/settings",
  guildChannels: "discord://guilds/{guildId}/channels",
  guildChannelOrder: "discord://guilds/{guildId}/channel-order",
  guildEmojis: "discord://guilds/{guildId}/emojis",
  guildRoles: "discord://guilds/{guildId}/roles",
  guildRoleOrder: "discord://guilds/{guildId}/role-order",
  roleDeletionReadiness: "discord://guilds/{guildId}/roles/{roleId}/deletion-readiness",
  guildScheduledEvents: "discord://guilds/{guildId}/scheduled-events",
  guildSoundboard: "discord://guilds/{guildId}/soundboard",
  guildStickers: "discord://guilds/{guildId}/stickers",
  guildTemplates: "discord://guilds/{guildId}/templates",
  guildVoiceRegions: "discord://guilds/{guildId}/voice-regions",
  guildIntegrations: "discord://guilds/{guildId}/integrations",
  memberVoiceState: "discord://guilds/{guildId}/members/{userId}/voice-state",
  threadMembership: "discord://guilds/{guildId}/threads/{threadId}/members/{userId}",
  threadState: "discord://guilds/{guildId}/threads/{threadId}",
})

export const MCP_PROMPT_NAMES = Object.freeze({
  findGuildMembers: "find_guild_members",
  inspectGuildBan: "inspect_guild_ban",
  reviewAnnouncementCrosspost: "review_announcement_crosspost",
  reviewAnnouncementSubscription: "review_announcement_subscription",
  reviewApplicationEmojiChange: "review_application_emoji_change",
  reviewApplicationIntentEnablement: "review_application_intent_enablement",
  reviewInviteCreation: "review_invite_creation",
  reviewInviteDeletion: "review_invite_deletion",
  reviewOnboardingChange: "review_onboarding_change",
  reviewWelcomeScreenChange: "review_welcome_screen_change",
  reviewWidgetSettingsChange: "review_widget_settings_change",
  reviewGuildSettingsChange: "review_guild_settings_change",
  reviewGuildIncidentActionChange: "review_guild_incident_action_change",
  reviewGuildProfileChange: "review_guild_profile_change",
  reviewAttachmentMessage: "review_attachment_message",
  reviewAutomodChange: "review_automod_change",
  reviewChannelCreation: "review_channel_creation",
  reviewChannelDeletion: "review_channel_deletion",
  reviewChannelClone: "review_channel_clone",
  reviewChannelMetadataChange: "review_channel_metadata_change",
  reviewVoiceChannelStatusChange: "review_voice_channel_status_change",
  reviewChannelOrder: "review_channel_order",
  reviewChannelPermissionOverwrite: "review_channel_permission_overwrite",
  reviewForumPost: "review_forum_post",
  reviewForumTagChange: "review_forum_tag_change",
  reviewGuildExpressionChange: "review_guild_expression_change",
  reviewGuildBlueprint: "review_guild_blueprint",
  reviewGuildTemplateChange: "review_guild_template_change",
  reviewGuildIntegrationDeletion: "review_guild_integration_deletion",
  reviewSoundboardChange: "review_soundboard_change",
  reviewGuildScaffold: "review_guild_scaffold",
  reviewBulkGuildBan: "review_bulk_guild_ban",
  reviewGuildPrune: "review_guild_prune",
  reviewMemberModeration: "review_member_moderation",
  reviewMemberNicknameChange: "review_member_nickname_change",
  reviewMemberRoleChange: "review_member_role_change",
  reviewMemberVoiceChange: "review_member_voice_change",
  reviewThreadChange: "review_thread_change",
  reviewMessageDeletion: "review_message_deletion",
  reviewMessageForward: "review_message_forward",
  reviewMessagePin: "review_message_pin",
  reviewReactionModeration: "review_reaction_moderation",
  reviewPendingNativeInteractions: "review_pending_native_interactions",
  reviewRoleCreation: "review_role_creation",
  reviewRoleConfiguration: "review_role_configuration",
  reviewRoleDeletion: "review_role_deletion",
  reviewRoleOrder: "review_role_order",
  reviewScheduledEventChange: "review_scheduled_event_change",
  reviewStageInstanceChange: "review_stage_instance_change",
  reviewWebhookChange: "review_webhook_change",
  reviewWebhookCreation: "review_webhook_creation",
  reviewWebhookDeletion: "review_webhook_deletion",
  searchGuildMessages: "search_guild_messages",
  summarizeChannel: "summarize_channel",
})

export type McpPromptName = typeof MCP_PROMPT_NAMES[
  keyof typeof MCP_PROMPT_NAMES
]

export const MCP_PROMPT_TOOLSETS = Object.freeze({
  [MCP_PROMPT_NAMES.findGuildMembers]: "members",
  [MCP_PROMPT_NAMES.inspectGuildBan]: "bans",
  [MCP_PROMPT_NAMES.reviewAnnouncementCrosspost]: "announcement-crossposts",
  [MCP_PROMPT_NAMES.reviewAnnouncementSubscription]: "announcement-subscriptions",
  [MCP_PROMPT_NAMES.reviewApplicationEmojiChange]: "application-emojis",
  [MCP_PROMPT_NAMES.reviewApplicationIntentEnablement]: "application-security",
  [MCP_PROMPT_NAMES.reviewInviteCreation]: "invites",
  [MCP_PROMPT_NAMES.reviewInviteDeletion]: "invites",
  [MCP_PROMPT_NAMES.reviewOnboardingChange]: "onboarding",
  [MCP_PROMPT_NAMES.reviewWelcomeScreenChange]: "welcome-screen",
  [MCP_PROMPT_NAMES.reviewWidgetSettingsChange]: "widget-settings",
  [MCP_PROMPT_NAMES.reviewGuildSettingsChange]: "guild-settings",
  [MCP_PROMPT_NAMES.reviewGuildIncidentActionChange]: "guild-incidents",
  [MCP_PROMPT_NAMES.reviewGuildProfileChange]: "guild-profile",
  [MCP_PROMPT_NAMES.reviewAttachmentMessage]: "attachments",
  [MCP_PROMPT_NAMES.reviewAutomodChange]: "automod",
  [MCP_PROMPT_NAMES.reviewChannelCreation]: "channel-creation",
  [MCP_PROMPT_NAMES.reviewChannelDeletion]: "channel-deletion",
  [MCP_PROMPT_NAMES.reviewChannelClone]: "channel-cloning",
  [MCP_PROMPT_NAMES.reviewChannelMetadataChange]: "channel-metadata",
  [MCP_PROMPT_NAMES.reviewVoiceChannelStatusChange]: "channel-metadata",
  [MCP_PROMPT_NAMES.reviewChannelOrder]: "channel-ordering",
  [MCP_PROMPT_NAMES.reviewChannelPermissionOverwrite]: "permission-overwrites",
  [MCP_PROMPT_NAMES.reviewForumPost]: "forum-posts",
  [MCP_PROMPT_NAMES.reviewForumTagChange]: "forum-tags",
  [MCP_PROMPT_NAMES.reviewGuildExpressionChange]: "guild-expressions",
  [MCP_PROMPT_NAMES.reviewGuildBlueprint]: "guild-blueprints",
  [MCP_PROMPT_NAMES.reviewGuildTemplateChange]: "guild-templates",
  [MCP_PROMPT_NAMES.reviewGuildIntegrationDeletion]: "integrations",
  [MCP_PROMPT_NAMES.reviewSoundboardChange]: "soundboard",
  [MCP_PROMPT_NAMES.reviewGuildScaffold]: "guild-scaffolds",
  [MCP_PROMPT_NAMES.reviewBulkGuildBan]: "bulk-bans",
  [MCP_PROMPT_NAMES.reviewGuildPrune]: "guild-prunes",
  [MCP_PROMPT_NAMES.reviewMemberModeration]: "moderation",
  [MCP_PROMPT_NAMES.reviewMemberNicknameChange]: "member-nicknames",
  [MCP_PROMPT_NAMES.reviewMemberRoleChange]: "member-roles",
  [MCP_PROMPT_NAMES.reviewMemberVoiceChange]: "voice-moderation",
  [MCP_PROMPT_NAMES.reviewThreadChange]: "thread-governance",
  [MCP_PROMPT_NAMES.reviewMessageDeletion]: "deletion",
  [MCP_PROMPT_NAMES.reviewMessageForward]: "message-forwarding",
  [MCP_PROMPT_NAMES.reviewMessagePin]: "pins",
  [MCP_PROMPT_NAMES.reviewReactionModeration]: "interactions",
  [MCP_PROMPT_NAMES.reviewPendingNativeInteractions]: "native-interactions",
  [MCP_PROMPT_NAMES.reviewRoleCreation]: "role-creation",
  [MCP_PROMPT_NAMES.reviewRoleConfiguration]: "role-configuration",
  [MCP_PROMPT_NAMES.reviewRoleDeletion]: "role-deletion",
  [MCP_PROMPT_NAMES.reviewRoleOrder]: "role-ordering",
  [MCP_PROMPT_NAMES.reviewScheduledEventChange]: "scheduled-events",
  [MCP_PROMPT_NAMES.reviewStageInstanceChange]: "stage-instances",
  [MCP_PROMPT_NAMES.reviewWebhookChange]: "webhooks",
  [MCP_PROMPT_NAMES.reviewWebhookCreation]: "webhooks",
  [MCP_PROMPT_NAMES.reviewWebhookDeletion]: "webhooks",
  [MCP_PROMPT_NAMES.searchGuildMessages]: "messages",
  [MCP_PROMPT_NAMES.summarizeChannel]: "messages",
} satisfies Record<McpPromptName, McpToolsetName>)

export function selectedMcpPromptNames(
  toolsets: ReadonlySet<McpToolsetName>,
): McpPromptName[] {
  return (Object.values(MCP_PROMPT_NAMES) as McpPromptName[])
    .filter((name) => toolsets.has(MCP_PROMPT_TOOLSETS[name]))
}
