export const MCP_TOOL_RISK_CLASSES = Object.freeze({
  add_reaction: "interaction-write",
  delete_messages: "destructive-write",
  discover_discord_tools: "local-read",
  edit_own_message: "interaction-write",
  execute_attachment_message: "interaction-write",
  execute_channel_creation: "administrative-write",
  execute_forum_post: "interaction-write",
  execute_guild_scaffold: "administrative-write",
  execute_member_moderation: "destructive-write",
  execute_role_creation: "administrative-write",
  audit_channel_role_access: "discord-read",
  explain_channel_access: "discord-read",
  explain_principal_permissions: "discord-read",
  get_guild_audit_entry: "discord-read",
  get_connector_status: "discord-read",
  get_gateway_events: "local-read",
  get_gateway_status: "local-read",
  get_message: "discord-read",
  get_observability_status: "local-read",
  get_role: "discord-read",
  list_active_threads: "discord-read",
  list_activity: "local-read",
  list_archived_threads: "discord-read",
  list_channels: "discord-read",
  list_guilds: "discord-read",
  list_guild_audit_entries: "discord-read",
  list_roles: "discord-read",
  plan_member_moderation: "discord-read",
  plan_attachment_message: "discord-read",
  plan_channel_creation: "discord-read",
  plan_forum_post: "discord-read",
  plan_guild_scaffold: "discord-read",
  plan_message_deletion: "discord-read",
  plan_role_creation: "discord-read",
  read_messages: "discord-read",
  search_messages: "discord-read",
  send_message: "interaction-write",
})

export type McpToolName = keyof typeof MCP_TOOL_RISK_CLASSES
export type McpToolRiskClass = typeof MCP_TOOL_RISK_CLASSES[McpToolName]

export const DISCORD_REST_OPERATIONS = Object.freeze({
  add_own_reaction: "PUT",
  bulk_delete_messages: "POST",
  create_guild_ban: "PUT",
  create_guild_channel: "POST",
  create_forum_post: "POST",
  create_guild_role: "POST",
  create_attachment_message: "POST",
  create_message: "POST",
  delete_message: "DELETE",
  edit_message: "PATCH",
  get_channel: "GET",
  get_current_application: "GET",
  get_current_user: "GET",
  get_guild: "GET",
  get_guild_audit_log: "GET",
  get_guild_ban: "GET",
  get_guild_channels: "GET",
  get_guild_member: "GET",
  get_guild_roles: "GET",
  get_guild_role: "GET",
  get_message: "GET",
  get_thread_member: "GET",
  get_user: "GET",
  list_active_guild_threads: "GET",
  list_current_user_guilds: "GET",
  list_joined_private_archived_threads: "GET",
  list_messages: "GET",
  list_private_archived_threads: "GET",
  list_public_archived_threads: "GET",
  modify_guild_member_timeout: "PATCH",
  remove_guild_ban: "DELETE",
  remove_guild_member: "DELETE",
  search_guild_messages: "GET",
})

export type DiscordRestOperation = keyof typeof DISCORD_REST_OPERATIONS
export type DiscordRestMethod = typeof DISCORD_REST_OPERATIONS[DiscordRestOperation]
